name: Continuous Integration

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install
        run: npm install
      
      - name: Run Cypress UI test
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          browser: edge
